--------------------------------------------------------
--  File created - Friday-December-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table admin
--------------------------------------------------------

  CREATE TABLE "admin" ("taikhoan" VARCHAR2(255), "password" VARCHAR2(255), "bophan" VARCHAR2(255))
--------------------------------------------------------
--  DDL for Table passport
--------------------------------------------------------

  CREATE TABLE "passport" ("id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , "hoten" VARCHAR2(255), "diachithuongtru" VARCHAR2(255), "gioitinh" VARCHAR2(255), "cmnd" VARCHAR2(255), "sodienthoai" VARCHAR2(255), "email" VARCHAR2(255), "xt_flag" NUMBER DEFAULT 0, "xt_user" VARCHAR2(255), "xt_time" DATE, "xd_flag" NUMBER DEFAULT 0, "xd_user" VARCHAR2(255), "xd_time" DATE, "lt_flag" NUMBER DEFAULT 0, "lt_user" VARCHAR2(255), "lt_time" DATE, "ghichu" VARCHAR2(255))
--------------------------------------------------------
--  DDL for Table resident
--------------------------------------------------------

  CREATE TABLE "resident" ("cmnd" VARCHAR2(255), "hoten" VARCHAR2(255), "diachithuongtru" VARCHAR2(255), "gioitinh" VARCHAR2(255), "dienthoai" VARCHAR2(255), "email" VARCHAR2(255), "tenbo" VARCHAR2(255), "tenme" VARCHAR2(255))
REM INSERTING into "admin"
SET DEFINE OFF;
Insert into "admin" ("taikhoan","password","bophan") values ('xacthuc','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92','xt');
Insert into "admin" ("taikhoan","password","bophan") values ('giamsat','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92','gs');
Insert into "admin" ("taikhoan","password","bophan") values ('luutru','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92','lt');
Insert into "admin" ("taikhoan","password","bophan") values ('xetduyet','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92','xd');
REM INSERTING into "passport"
SET DEFINE OFF;
Insert into "passport" ("id","hoten","diachithuongtru","gioitinh","cmnd","sodienthoai","email","xt_flag","xt_user","xt_time","xd_flag","xd_user","xd_time","lt_flag","lt_user","lt_time","ghichu") values (1,'test','test','Nam','123456789','1231231231','aaaa@gmail.com',0,null,null,0,null,null,0,null,null,null);
REM INSERTING into "resident"
SET DEFINE OFF;
Insert into "resident" ("cmnd","hoten","diachithuongtru","gioitinh","dienthoai","email","tenbo","tenme") values ('123456789','zzzz','aaaaa','Nam','1231232','sadsd@gmail.com','aAAAA','AAAAA');
--------------------------------------------------------
--  DDL for Index admin_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "admin_PK" ON "admin" ("taikhoan")
--------------------------------------------------------
--  DDL for Index passport_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "passport_PK" ON "passport" ("id")
--------------------------------------------------------
--  DDL for Index resident_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "resident_PK" ON "resident" ("cmnd")
--------------------------------------------------------
--  Constraints for Table admin
--------------------------------------------------------

  ALTER TABLE "admin" MODIFY ("taikhoan" NOT NULL ENABLE)
  ALTER TABLE "admin" ADD CONSTRAINT "admin_PK" PRIMARY KEY ("taikhoan") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table passport
--------------------------------------------------------

  ALTER TABLE "passport" MODIFY ("id" NOT NULL ENABLE)
  ALTER TABLE "passport" ADD CONSTRAINT "passport_PK" PRIMARY KEY ("id") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table resident
--------------------------------------------------------

  ALTER TABLE "resident" MODIFY ("cmnd" NOT NULL ENABLE)
  ALTER TABLE "resident" ADD CONSTRAINT "resident_PK" PRIMARY KEY ("cmnd") USING INDEX  ENABLE
